# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: gibd
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
